[[redirects]]
  from = "/api/*"
  to = "https://gestaofinanceira-backend.onrender.com/:splat" # Substitua pela URL do Render ou da VM
  status = 200
  force = true # Garante que a regra seja aplicada

# Regra fallback para o React Router funcionar corretamente
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
